version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys: 
          fingerprints: 
            - "7d:ab:66:3c:75:01:a2:39:04:f4:0f:f1:ce:3c:8c:92"
      - checkout 
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build