version: 2
jobs:
  build:
    branches:
      only: 
        - master
    docker:
      - image: circleci/node:12
    steps:
      - add_ssh_keys:
          fingerprints:
            - "7d:ab:66:3c:75:01:a2:39:04:f4:0f:f1:ce:3c:8c:92"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build